# =====================================================
# APPLICATION
# =====================================================

spring.application.name=generator
server.port=9022


# =====================================================
# GEMINI API
# =====================================================

spring.ai.google.genai.api-key=

# optional
spring.ai.google.genai.chat.api-key=
spring.ai.google.genai.embedding.api-key=

# =====================================================
# GEMINI MODEL CONFIG
# =====================================================

spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.ai.google.genai.chat.options.temperature=0.2

spring.ai.google.genai.embedding.options.model=text-embedding-004

spring.ai.retry.max-attempts=2


# =====================================================
# VECTOR STORE
# =====================================================

spring.ai.vectorstore.pgvector.dimensions=768

spring.ai.vectorstore.pgvector.initialize-schema=true


# =====================================================
# DATABASE
# =====================================================

spring.datasource.url=jdbc:postgresql://localhost:5433/insight

spring.datasource.username=

spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver


# =====================================================
# SQL / JPA
# =====================================================

spring.sql.init.mode=never

spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# ANOMALY AGENT CONFIG
# =====================================================

# run every 15 mins
anomaly.agent.polling-rate=90000

# duplicate suppression
anomaly.agent.suppression-hours=1

# thresholds
anomaly.agent.threshold.quality-score=0.60

anomaly.agent.threshold.quality-drops=6

anomaly.agent.threshold.latency=200

anomaly.agent.threshold.device-drops=6000


# =====================================================
# LOGGING
# =====================================================

logging.level.org.springframework.web=INFO

logging.level.org.springframework.jdbc=INFO

logging.level.org.hibernate.SQL=ERROR

logging.level.com.telecom.insights=INFO


# =====================================================
# DOCKER
# =====================================================

spring.docker.compose.lifecycle-management=start_only