spring.application.name=ingestion-service
server.port=9021

# ==========================================
# DATABASE CONFIGURATION
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/insight
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# KAFKA CONSUMER CONFIGURATION
# ==========================================
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=telecom-ingestion-group
spring.kafka.consumer.auto-offset-reset=latest

# Deserialize JSON directly into Java Maps
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*